version: "2"
services:
  mysql:
    image: mysql
    hostname: mysql.robin.examples
    environment:
       - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
       - /tmp/mysql:/var/lib/mysql

  qpid:
    image: indexing/qpid
    hostname: qpid.robin.examples

  redis:
    image: redis:3.2-alpine
    hostname: redis.robin.examples